mongo_csv_location = "/home/openandroid/Documents/output/mongo_csv_output.csv"
mongo_json_location = "/home/openandroid/Documents/output/mongo_json_output.json"
mongo_xml_location = "/home/openandroid/Documents/output/mongo_xml_output.xml"
solr_csv_location = "/home/openandroid/Documents/output/solr_csv_output.csv"
solr_json_location = "/home/openandroid/Documents/output/solr_json_output.json"
solr_xml_location = "/home/openandroid/Documents/output/solr_xml_output.xml"