threads = 8
jdk = "java"
encoding = "-Dfile.encoding=UTF-8"
classpath = "-cp .:Rapid.jar"
api_java_file = "APIParser"
string_java_file = "StringParser"
solr_dir = "/opt/solr-6.1.0"
solr_collection_name = "apps"
json_dir = "/home/openandroid/Documents/solr_json/"
mongo_json = "/home/openandroid/Documents/mongo_json/"
apk_dir = "/home/openandroid/Documents/apks/"
permissions_list = "/home/openandroid/Documents/Code/permissions_list.txt"
sys_cmd_list = "/home/openandroid/Documents/Code/Code/sys_cmd_list.txt"
solr_dir = "/opt/solr/"
decoded_apk_dir = "/home/openandroid/Documents/decodedapks/"